baseURL = "https://www.carl-schirm.de/"
languageCode = "de-DE"
title = "Carl Schirm"
theme = "carlschirm"

# copyright

[params]
    iconset = "https://use.fontawesome.com/releases/v5.3.1/js/all.js"
    
    description = "Im Gewerbepark Carl Schirm zwischen Tübingen und Reutlingen finden Sie auf historischem Areal Lager-, Service- und Produktionsflächen sowie Büroräume, die äußerst flexibel gestaltet werden können. Unter den bereits angesiedelten Firmen aus unterschiedlichen Branchen befinden sich Produktionsbetriebe, Handel, Internetshops, Dienstleistungen, Ingenieurbüros, junge Gründerfirmen, Labore, Lager sowie Handwerksbetriebe."

    keywords = ["Gewerbe", "Gewerbepark", "Gewerberaum", "Gewerberäume", "Gewerbefläche",
    "Gewerbe mieten", "Gewerberaum mieten", "Gewerberäume mieten", "Gewerbefläche mieten",
    "Carl Schirm", 
    "Reutlingen", "Tübingen", "Kirchentellinsfurt", "Stuttgart", 
    "Vermietung", "mieten", 
    "Servicefläche", "Produktionsfläche", "Lager", "Produktion", "Handel", "Dienstleistung", "Büro", "Gründerfirma", "Startup", "Start-up", "Labor", "Handwerksbetrieb",
    "Produktionsfläche mieten", "Büro mieten", "Büroraum mieten"]

    # path to CSS file
    customCSS = ["/css/carlschirm/css/cs.css"]
    customJS = ["js/mobileNavbar.js"]

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logoFooter]
    url = "cs_logo_transparent.png"
    width = 120
    height = 125
    alt = "Logo Carl Schirm"

    [params.logo]
    url = "cs_fabrik.png"
    width = 120
    height = 120
    alt = "Gebäudeansicht Carl Schirm"

[sitemap]
    changefreq = "monthly"
    priority = 0.5
    filename = "sitemap.xml"