baseURL = "https://carlschirm.netlify.com/"
languageCode = "de-DE"
title = "Carl Schirm"
theme = "carlschirm"

# copyright

[params]
    iconset = "https://use.fontawesome.com/releases/v5.3.1/js/all.js"
    
    description = "Im Gewerbepark Carl Schirm zwischen Tübingen und Reutlingen finden Sie auf historischem Areal Lager-, Service- und Produktionsflächen sowie Büroräume, die äußerst flexibel gestaltet werden können. Unter den bereits angesiedelten Firmen aus unterschiedlichen Branchen befinden sich Produktionsbetriebe, Handel, Internetshops, Dienstleistungen, Ingenieurbüros, junge Gründerfirmen, Labore, Lager sowie Handwerksbetriebe."

    keywords = []

    # path to CSS file
    customCSS = ["/css/carlschirm/css/cs.css"]
    # , "/css/bulma_extensions/bulma-carousel.min.css" , "/css/iframes_responsive.css"
    customJS = ["js/mobileNavbar.js"]

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    logoFooter = "cs_stern_bw_nobg.png"

    [params.logo]
    url = "cs_fabrik.png"
    width = 120
    height = 120
    alt = "Carl Schirm"

[sitemap]
    changefreq = "monthly"
    priority = 0.5
    filename = "sitemap.xml"